Qemu minimum version checking added.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -103,6 +103,18 @@ option_board() {
     fi
 }
 
+package_install() {
+    PKG_DEBIAN=$1
+    PKG_GENTOO=$2
+    ENV_GENTOO=$3
+
+    INSTALL_DEBIAN="${INSTALL_DEBIAN} ${PKG_DEBIAN}"
+    if [ -n "${ENV_GENTOO}" ]; then
+	INSTALL_GENTOO="${ENV_GENTOO} ${INSTALL_GENTOO}"
+    fi
+    INSTALL_GENTOO="${INSTALL_GENTOO} ${PKG_GENTOO}"
+}
+
 # Check if a binary exists, and add it to the install list otherwise
 # $1: Test if the binary is necessary (set to 1 to force)
 # $2: The binary to test
@@ -117,17 +129,57 @@ package_check_binary() {
     ENV_GENTOO=$5
 
     if [ ${TEST} -ne 1 ]; then
-	return
+	return 1
     fi
 
     which ${BIN} &>/dev/null
     if [ $? -ne 0 ]; then
-	INSTALL_DEBIAN="${INSTALL_DEBIAN} ${PKG_DEBIAN}"
-	if [ -n "${ENV_GENTOO}" ]; then
-	    INSTALL_GENTOO="${ENV_GENTOO} ${INSTALL_GENTOO}"
-	fi
-	INSTALL_GENTOO="${INSTALL_GENTOO} ${PKG_GENTOO}"
+	package_install $3 $4 $5
+	return 1
     fi
+    return 0
+}
+
+# Check if a binary exists, in the specified version with the format X.Y.Z,
+# and add it to the install list otherwise
+# $1: Test if the binary is necessary (set to 1 to force)
+# $2: The binary to test
+# $3: The minimum expected version
+# $4: The Debian package name
+# $5: The Gentoo package name
+# $6: The optional Gentoo environment to install the package
+package_check_binary_version() {
+    package_check_binary $1 $2 $4 $5 $6
+
+    if [ $? -eq 1 ]; then
+	# The package must be installed, version checking is not necessary
+	return 1
+    fi
+
+    REGEX='s/.*([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 \2 \3/p'
+    VERSION=($($2 --version | sed -rne "${REGEX}"))
+
+    if [ -z "${VERSION}" ]; then
+	echo "Failed to check required version for \"$2\""
+	exit 1
+    fi
+
+    REQ_VERS=($(echo $3 | sed -rne "${REGEX}"))
+    if [ -z "${REQ_VERS}" ]; then
+	echo "Failed to parse the required version for \"$2\""
+	echo "It must be in the X.Y.Z format (X, Y and Z being numbers)"
+	exit 1
+    fi
+
+    for idx in $(seq 0 2); do
+	if [ ${VERSION[$idx]} -gt ${REQ_VERS[$idx]} ]; then
+	    return 0
+	elif [ ${VERSION[$idx]} -lt ${REQ_VERS[$idx]} ]; then
+	    echo "\"$2\" minimum version is $3, please update it"
+	    package_install $4 $5 $6
+	    return 1
+	fi
+    done
 }
 
 # Check that the required packages, depending on the target, are installed
@@ -140,8 +192,8 @@ packages_check() {
     package_check_binary 1 realpath realpath "realpath" "app-misc/realpath"
 
     # Checking that Qemu is installed
-    package_check_binary ${BOARD_QEMU} qemu-system-${QEMU_ARCH} "qemu-system" \
-	"\">=app-emulation/qemu-1.6.1\"" \
+    package_check_binary_version ${BOARD_QEMU} qemu-system-${QEMU_ARCH} \
+	"1.6.1" "qemu-system" "\">=app-emulation/qemu-1.6.1\"" \
 	"QEMU_SOFTMMU_TARGETS=${QEMU_ARCH} USE=fdt"
 
     # Checking that fakeroot, used by Busybox, is installed
